server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import:
      optional:configserver:


management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

tracing:
  sampling:
    probability: 1.0


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"